// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import React, { useState, useEffect, useRef } from 'react';
import { useOutlet, history } from 'dumi';
import { warning } from '/Users/user/Desktop/pixel-ui/pixel-ui-react/node_modules/.pnpm/rc-util@5.44.4_react-dom@19.2.0_react@19.2.0__react@19.2.0/node_modules/rc-util';
import { SiteContext, type ISiteContext } from '/Users/user/Desktop/pixel-ui/pixel-ui-react/node_modules/.pnpm/dumi@2.4.21_@babel+core@7.28.5_@swc+helpers@0.5.15_@types+node@24.6.2_@types+react@19.2_6df58e5a629c375829b22a9b952c9f81/node_modules/dumi/dist/client/theme-api/context.js';
import { components } from '../meta/atoms';
import { locales } from '../locales/config';
import entryDefaultExport from '/Users/user/Desktop/pixel-ui/pixel-ui-react/packages/docs/src/index.tsx';


const entryExports = {
    default: entryDefaultExport,
};

// Static content
const pkg = {"name":"@pixel-ui-react/docs","description":"Pixel UI React 组件库文档","version":"1.0.0","license":"ISC","author":""};
const historyType = "browser";
const hostname = undefined;
const themeConfig = {"title":"Pixel UI React","footer":"Copyright © 2025 Pixel UI React","prefersColor":{"default":"light","switch":false},"nprogress":true,"lastUpdated":true,"name":"Pixel UI React","logo":"/pixel-ui-react/images/homelogo.png","nav":[{"title":"开始使用","link":"/getting-started"},{"title":"组件","link":"/components/button"}],"socialLinks":{"github":"https://github.com/maomentai817/pixel-ui-react"}};
const _2_level_nav_available = true;

export default function DumiContextWrapper() {
  const outlet = useOutlet();
  const [loading, setLoading] = useState(false);
  const prev = useRef(history.location.pathname);

  useEffect(() => {
    return history.listen((next) => {
      if (next.location.pathname !== prev.current) {
        prev.current = next.location.pathname;

        // scroll to top when route changed
        document.documentElement.scrollTo(0, 0);
      }
    });
  }, []);

  const context: ISiteContext = React.useMemo(() => {
    const ctx = {
      pkg,
      historyType,
      entryExports,
      demos: null,
      components,
      locales,
      loading,
      setLoading,
      hostname,
      themeConfig,
      _2_level_nav_available,
    };

    // Proxy do not warning since `Object.keys` will get nothing to loop
    Object.defineProperty(ctx, 'demos', {
      get: () => {
        warning(false, '`demos` return empty in latest version, please use `useDemo` instead.');
        return {};
      },
    });

    return ctx;
  }, [
    pkg,
    historyType,
    entryExports,
    components,
    locales,
    loading,
    setLoading,
    hostname,
    themeConfig,
    _2_level_nav_available,
  ]);

  return (
    <SiteContext.Provider value={context}>
      {outlet}
    </SiteContext.Provider>
  );
}
