// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import { getPluginManager as getDumiPluginManager } from './core/plugin';
import { setPluginManager as setDumiPluginManager } from '/Users/user/Desktop/pixel-ui/pixel-ui-react/node_modules/.pnpm/dumi@2.4.21_@babel+core@7.28.5_@swc+helpers@0.5.15_@types+node@24.6.2_@types+react@19.2_6df58e5a629c375829b22a9b952c9f81/node_modules/dumi/dist/client/theme-api/utils.js';
import { getClientRootComponent } from '/Users/user/Desktop/pixel-ui/pixel-ui-react/node_modules/.pnpm/@umijs+renderer-react@4.5.3_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/@umijs/renderer-react/dist/server.js';
import { getRoutes } from './core/route';
import { createHistory as createClientHistory } from './core/history';
import { ServerInsertedHTMLContext } from './core/serverInsertedHTMLContext';
import { createPluginManager } from './core/plugin';
import createRequestHandler, { createMarkupGenerator, createUmiHandler, createUmiServerLoader, createAppRootElement } from '/Users/user/Desktop/pixel-ui/pixel-ui-react/node_modules/.pnpm/@umijs+server@4.5.3/node_modules/@umijs/server/dist/ssr.js';
import fs from 'fs';
import path from 'path';


// always remove trailing slash from location.pathname
if (
  typeof history !== 'undefined' &&
  location.pathname.length > 1 &&
  location.pathname.endsWith('/')
) {
  history.replaceState(
    {},
    '',
    location.pathname.slice(0, -1) + location.search + location.hash,
  );
}

typeof document !== 'undefined' && document.documentElement.setAttribute('data-prefers-color', 'light');
let helmetContext;

try {
  helmetContext = require('./core/helmetContext').context;
} catch { /* means `helmet: false`, do noting */ }

const routesWithServerLoader = {
};

export function getManifest(sourceDir) {
  let manifestPath;
  if (process.env.SSR_MANIFEST) {
    return JSON.parse(process.env.SSR_MANIFEST)
  } 
  if (sourceDir) {
    manifestPath = path.join(sourceDir,'build-manifest.json')
  }
  else {
    manifestPath = '/Users/user/Desktop/pixel-ui/pixel-ui-react/packages/docs/dist/build-manifest.json'
  }
  if (fs.existsSync(manifestPath)) {
    return JSON.parse(fs.readFileSync(manifestPath), 'utf-8');
  }
  return {
    assets: {}
  }
}

export function createHistory(opts) {
  return createClientHistory(opts);
}

// TODO: remove global variable
global.g_getAssets = (fileName) => {
  let m = getManifest();
  return m.assets[fileName];
};
const createOpts = {
  routesWithServerLoader,
  reactVersion: '19.2.0',
  pluginManager: createPluginManager(),
  getRoutes,
  manifest: getManifest,
  getClientRootComponent,
  helmetContext,
  createHistory,
  ServerInsertedHTMLContext,
  htmlPageOpts: {"headScripts":[],"styles":[],"title":"Pixel UI React - 基于CSS Houdini的像素风React组件库","favicons":["/pixel-ui-react/images/favicon.ico"],"links":[{"rel":"icon","href":"/pixel-ui-react/images/favicon.ico"}],"metas":[{"name":"description","content":"基于CSS Houdini的像素风React组件库，支持像素风格渲染、自定义像素字体和像素边框，致力于打造独特的Web UI体验。"},{"name":"keywords","content":"Pixel UI,React,组件库,像素风格,CSS Houdini,TypeScript,UI组件,像素风,React组件库,Pixel UI React"},{"name":"author","content":"Pixel UI React Team"},{"name":"robots","content":"index, follow"},{"name":"viewport","content":"width=device-width, initial-scale=1.0"},{"name":"theme-color","content":"#ffffff"},{"property":"og:type","content":"website"},{"property":"og:title","content":"Pixel UI React - 基于CSS Houdini的像素风React组件库"},{"property":"og:description","content":"基于CSS Houdini的像素风React组件库，支持像素风格渲染、自定义像素字体和像素边框，致力于打造独特的Web UI体验。"},{"property":"og:image","content":"/pixel-ui-react/images/homelogo.png"},{"property":"og:url","content":"https://maomentai817.github.io/pixel-ui-react/"},{"property":"og:site_name","content":"Pixel UI React"},{"name":"twitter:card","content":"summary_large_image"},{"name":"twitter:title","content":"Pixel UI React - 基于CSS Houdini的像素风React组件库"},{"name":"twitter:description","content":"基于CSS Houdini的像素风React组件库，支持像素风格渲染、自定义像素字体和像素边框，致力于打造独特的Web UI体验。"},{"name":"twitter:image","content":"/pixel-ui-react/images/homelogo.png"}],"scripts":[]},
 __INTERNAL_DO_NOT_USE_OR_YOU_WILL_BE_FIRED: {"pureApp":false,"pureHtml":false},
  mountElementId: 'root',
  basename: '/pixel-ui-react/',
  useStream: true
};
const requestHandler = createRequestHandler(createOpts);
/**
 * @deprecated  Please use `requestHandler` instead.
 */
export const renderRoot = createUmiHandler(createOpts);
/**
 * @deprecated  Please use `requestHandler` instead.
 */
export const serverLoader = createUmiServerLoader(createOpts);

export const _markupGenerator = createMarkupGenerator(createOpts);

export const getAppRootElement = createAppRootElement.bind(null, createOpts)();

export default requestHandler;

export const g_umi = '4.5.3'


    if (typeof window !== 'undefined') {
      window.g_umi = {
        version: '4.5.3',
      };
    }
    
setDumiPluginManager(getDumiPluginManager());
