// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import React from 'react';

export async function getRoutes() {
  const routes = {"404":{"id":"404","path":"*","parentId":"DocLayout"},"dumi-context-layout":{"id":"dumi-context-layout","path":"/","isLayout":true,"hasServerLoader":false,"hasMetadataLoader":false},"DocLayout":{"id":"DocLayout","path":"/","parentId":"dumi-context-layout","isLayout":true},"index":{"path":"","id":"index","parentId":"DocLayout","hasServerLoader":false,"hasMetadataLoader":false},"docs/components/button":{"path":"components/button","id":"docs/components/button","parentId":"DocLayout"},"docs/getting-started":{"path":"getting-started","id":"docs/getting-started","parentId":"DocLayout"},"demo-render":{"id":"demo-render","path":"~demos/:id","parentId":"dumi-context-layout","prerender":false}} as const;
  return {
    routes,
    routeComponents: {
'404': React.lazy(() => import(/* webpackChunkName: "nm__dumi__dist__client__pages__404" */'/Users/user/Desktop/pixel-ui/pixel-ui-react/node_modules/.pnpm/dumi@2.4.21_@babel+core@7.28.5_@swc+helpers@0.5.15_@types+node@24.6.2_@types+react@19.2_6df58e5a629c375829b22a9b952c9f81/node_modules/dumi/dist/client/pages/404.js')),
'dumi-context-layout': React.lazy(() => import(/* webpackChunkName: "dumi__tmp-production__dumi__theme__ContextWrapper" */'/Users/user/Desktop/pixel-ui/pixel-ui-react/packages/docs/.dumi/tmp-production/dumi/theme/ContextWrapper')),
'DocLayout': React.lazy(() => import(/* webpackChunkName: "nm__dumi__theme-default__layouts__DocLayout__index" */'/Users/user/Desktop/pixel-ui/pixel-ui-react/node_modules/.pnpm/dumi@2.4.21_@babel+core@7.28.5_@swc+helpers@0.5.15_@types+node@24.6.2_@types+react@19.2_6df58e5a629c375829b22a9b952c9f81/node_modules/dumi/theme-default/layouts/DocLayout/index.js')),
'index': React.lazy(() => import(/* webpackChunkName: "dumi__pages__index" */'/Users/user/Desktop/pixel-ui/pixel-ui-react/packages/docs/.dumi/pages/index.tsx')),
'docs/components/button': React.lazy(() => import(/* webpackChunkName: "docs__components__button.md" */'/Users/user/Desktop/pixel-ui/pixel-ui-react/packages/docs/docs/components/button.md')),
'docs/getting-started': React.lazy(() => import(/* webpackChunkName: "docs__getting-started.md" */'/Users/user/Desktop/pixel-ui/pixel-ui-react/packages/docs/docs/getting-started.md')),
'demo-render': React.lazy(() => import(/* webpackChunkName: "nm__dumi__dist__client__pages__Demo__index" */'/Users/user/Desktop/pixel-ui/pixel-ui-react/node_modules/.pnpm/dumi@2.4.21_@babel+core@7.28.5_@swc+helpers@0.5.15_@types+node@24.6.2_@types+react@19.2_6df58e5a629c375829b22a9b952c9f81/node_modules/dumi/dist/client/pages/Demo/index.js')),
},
  };
}
