// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
export type {
  // server loader
  IServerLoaderArgs,
  UmiRequest,
  ServerLoader,
  // metadata loader
  MetadataLoader,
  IMetadata,
  IMetaTag,
} from '/Users/user/Desktop/pixel-ui/pixel-ui-react/node_modules/.pnpm/@umijs+server@4.5.3/node_modules/@umijs/server/dist/types'
